DROP TABLE IF EXISTS STUDENT_GROUP;
CREATE TABLE STUDENT_GROUP(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), STUDENT_ID BIGINT);
DROP TABLE IF EXISTS COURSE;
CREATE TABLE COURSE(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), STUDENT_ID BIGINT);
DROP TABLE IF EXISTS STUDENTS;
CREATE TABLE STUDENTS(ID BIGINT PRIMARY KEY, SECOND_NAME VARCHAR(255), FIRST_NAME VARCHAR(255), BATYA_NAME VARCHAR(255), GROUP_ID BIGINT, COURSE_ID BIGINT, MARK BIGINT);


ALTER TABLE STUDENT_GROUP ADD FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS (ID)
ALTER TABLE COURSE ADD FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS (ID)
ALTER TABLE STUDENT ADD FOREIGN KEY(GROUP_ID) REFERENCES STUDENT_GROUP (STUDENT_ID)
ALTER TABLE STUDENT ADD FOREIGN KEY(COURSE_ID) REFERENCES COURSE (STUDENT_ID)